public virtual class IntegrationService implements IIntegrationService {

    public IntegrationService() {

    }

    public virtual Object processGet(String jsonBody) {
       return null;
    }

    public virtual Object processPost(String jsonBody) {
        return null;
    }

    public virtual Object processPut(String jsonBody) {
        return null;
    }

    public virtual Object processPatch(String jsonBody) {
        return null;
    }

    public virtual Object processDelete(String jsonBody) {
        return null;
    }

}
